language: c

os:
  - linux
  - osx

dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libao-dev libfftw3-dev librtlsdr-dev mingw-w64 python3-pyaudio; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libao fftw librtlsdr xz mingw-w64 portaudio wine; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install pyaudio; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then CC= ../support/win-cross-compile 32; fi
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then CC= ../support/win-cross-compile 64; fi

script:
  - xz -d < ../support/sample.xz > sample
  - nrsc5 -r sample -o sample.wav 0 2> sample.log
  - cat sample.log
  - grep -q "You're Listening to Q" sample.log
  - cat sample | nrsc5 -r - -o sample.wav 0 2> sample.log
  - grep -q "You're Listening to Q" sample.log
  - ../support/nrsc5.py -r sample 0 0
  - cat sample | ../support/nrsc5.py -r - 0 0
  - if [[ "TRAVIS_OS_NAME" == "osx" && "$TRAVIS_COMPILER" == "gcc" ]]; then wine ../build-win32/bin/nrsc5.exe -r sample -o sample.wav 0 2> sample.log && grep -q "You're Listening to Q" sample.log; fi
  - if [[ "TRAVIS_OS_NAME" == "osx" && "$TRAVIS_COMPILER" == "gcc" ]]; then wine ../build-win64/bin/nrsc5.exe -r sample -o sample.wav 0 2> sample.log && grep -q "You're Listening to Q" sample.log; fi
